language: node_js
node_js:
- '10'
services:
- docker
before_install:
- sudo apt update
- sudo apt install libcairo2-dev libjpeg-dev libgif-dev
- npm install
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash publish.sh
  on:
    tags: true
env:
  global:
  - secure: K77p7UBXQ1OE0j2MizHI7TDU0dqbOXOe8krkfaPK5PnMFCt89nhdS9VvT167YjnXCmDL6ragiUlHDOMH5zk2GS1gXcWEVbGsvHsnFLRg5jEJr/fk8onG5v66p+99QSPWPTkH3SMTMv6ru5oH12r7ulo9xVxV8tK/C2176wMT6AGAFu466aBxCng/9o7ynrswPH/ePLMf0TP3xt8Qa55+YkMZCFpUgaqQxupyqn/hFf+5OvvlShb5SkbJ9mo0yzf2Nop/bBL2FQMWy7/dybkFEFHPDFkd1d5+lMT+lvjq0iCMxWcnH5bDaLRNZSFBPCgHLLELG81vcMemDI3x2Tm5VPmTRxUU55p24RYfn7xlq5eC6Rw9uh/0oXdvCDCmhW5sl7trCK+zK/uk2oz5c4pVD67zqTUPm95lR5SGjMn7K1prQVe9Oy4Zw9x+5mPvpEeDREiUSZm5iheHD33UozyW9yQP+BsYeYRNmRg1aL+/N3aS+N2fEaZdIslQUjmxi9c0QzIRgYV9oznNU0vANtAT1waj42nJQYmz2WBG7DOGMI19AGXehsLMIsmJnvAuUA69+qfwByDAwPyiyXM+wwl/1OXHkcdDnogC7wZwGKM7JuPPRgnOV+ptibLKVnbCwa0mSIWW5te1LPtotkSkzAvTBUbhC2Eo7GuBl4bWcqtfXR4=
  - secure: K+t6SqMK8zOg4G3s5THIRgyC0V0+mLXL4XiYsLRUpWD9ihgUge5Z+UhtQg/oR6gbGHe2lMfwZFGWK/qqwqIYtXUjtpBMz/Kohm8tWohS3D/baoYNtt1Oarth0X3p1MJ8lUj7UnQssIdQFBxqX2jTBnydjjFFrLQJeJU/CtBnQ1tJ9KhWKo80BC2ueKXW3xIgX8xN/zQV6VFgLlS5hCCKmsQ8Er1shRbuRma0RFzXu2GAiZnbQ93rLUKM37+9dRCxZc0QrLA9EGctRvzdEPU4Px5d1ynQT/8bdYnq1QhKj1y2kjBdXPMncv3BR6XHJk4kR0WRf9CIduj/IFlIkE5VRKNg2iquOl/+ksed1UaXbY214o7QDR6npKOVe6GB2wRY/qGOOk/ALvNHs/w1OGKKQnU9VoeF1wS7NuOxa641BLHJMYu8D0YNsjfzAfn4uu9Ij1vCCXGzB6vOedr5Uy4WH9mSiz1XTIXTffAYasw0Y9cM6jzyt4NdqPA2Ds+g0C5GCGYdGvpu42zss3VPSZ7AdR60kbp3T+kIIp0mtTYjYeKIaZI6tJEVdOaZnaI/iWjKkm+G9Kskwksypzv3npZDW62hvR4SMuawj5IBMbe+Bkp5ixqtgBEY3EMR3kScBEGOJUoK2iF0jjNFJdlFXyCKY94EeWGRAvIdiUyIVJednTQ=
